config/routes.rb
Rails.application.routes.draw do
  resources :meetings
  devise_for :users
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  extend FriendlyId
  friendly_id :username, use: :slugged

  has_many :meetings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :username])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
before_action :authenticate_user!
before_action :set_meeting, except: [:index, :new, :create]

  def index
    @meetings = current_user.meetings.all
  end

  def show
  end

  def new
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id

    respond_to do |format|
      if @meeting.save
        format.html {redirect_to @meeting, notice: "Meeting was successfully created."}
        format.json {render :show, status: :created, location: @meeting}
      else
        format.html {render :new}
        format.json {render json: @meeting.erros, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update

  end

  def destroy

  end

  private

  def set_meeting
    @meeting = Meeting.friendly.find(params[:id])
  end

  def meeting_params
    params.require(:meeting).permit(:name, :start_time, :end_time, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def readable_time(time)
    time.strftime("%b %d, %I:%M%P")
  end

  def author_of(record)
    user_signed_in? && current_user.id == record.user_id
  end

  def admin?
    user_signed_in? && current_user.admin?
  end
end

app/helpers/mettings_helper.rb
module MettingsHelper
end

app/views/home/index.html.erb
<h1> Hello </h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "HereForYou", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Schedule new session", new_meeting_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Scheduling</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
      <% if type == "alert" %>
        <div>
          <%= message %>
        </div>
      <% end %>
      <% if type == "notice" %>
        <%= message %>
      <% end %>
    <% end %>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <div class="container">
        <%= content_for?(:content) ? yield(:content) : yield %>
      </div>
    </main>
  </body>
</html>

app/views/meetings/_form.html.erb
<%= form_with(model: meeting, local:true) do |form| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2> <%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>
      <ul>
        <% meeting.errors.full_messages.each do |message| %>
          <li> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :start_time %>
    <%= form.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= form.label :end_time %>
    <%= form.datetime_select :end_time %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meetings/index.html.erb
<h1> Hello </h1>
<%= link_to 'New meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>Schedule a new session</h1>
<p>Schedule a new consulting session by choosing the best time that works for you below.</p>

<%= render 'form', meeting: @meeting %>

app/views/meetings/show.html.erb
<h1><%= @meeting.name %></h1>
<p><%= @meeting.start_time %></p>
<p><%= @meeting.end_time %></p>